/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#005236",
        "on-primary-container": "#80bea6",
        "on-tertiary-fixed": "#2a1700",
        "background": "#f9f9ff",
        "surface-variant": "#dce2f3",
        "surface-container-high": "#e2e8f8",
        "inverse-on-surface": "#ebf1ff",
        "on-surface-variant": "#404944",
        "on-tertiary": "#ffffff",
        "primary-container": "#064e3b",
        "surface-container": "#e7eefe",
        "secondary-fixed": "#6ffbbe",
        "outline": "#707974",
        "tertiary-container": "#623c00",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-surface": "#151c27",
        "surface-bright": "#f9f9ff",
        "surface-container-highest": "#dce2f3",
        "surface": "#f9f9ff",
        "tertiary-fixed": "#ffddb8",
        "tertiary": "#442800",
        "secondary": "#006c49",
        "on-primary-fixed": "#002117",
        "on-tertiary-fixed-variant": "#653e00",
        "secondary-container": "#6cf8bb",
        "surface-container-low": "#f0f3ff",
        "on-background": "#151c27",
        "surface-container-lowest": "#ffffff",
        "primary": "#003527",
        "surface-dim": "#d3daea",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#f69f0d",
        "on-error": "#ffffff",
        "surface-tint": "#2b6954",
        "on-secondary-fixed": "#002113",
        "inverse-surface": "#2a313d",
        "primary-fixed-dim": "#95d3ba",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#0b513d",
        "on-secondary-container": "#00714d",
        "tertiary-fixed-dim": "#ffb95f",
        "secondary-fixed-dim": "#4edea3",
        "primary-fixed": "#b0f0d6",
        "outline-variant": "#bfc9c3",
        "inverse-primary": "#95d3ba"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "2xl": "48px",
        "margin-desktop": "40px",
        "gutter": "24px",
        "base": "4px",
        "lg": "24px",
        "xs": "4px",
        "margin-mobile": "16px",
        "md": "16px",
        "xl": "32px",
        "sm": "8px"
      },
      fontFamily: {
        "label-md": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
